// Mocks generated by Mockito 5.4.6 from annotations
// in storage_app/test/screens/item_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:storage_app/domain/entities/item.dart' as _i2;
import 'package:storage_app/domain/entities/location.dart' as _i3;
import 'package:storage_app/domain/repositories/item_repository.dart' as _i4;
import 'package:storage_app/domain/repositories/location_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeItem_0 extends _i1.SmartFake implements _i2.Item {
  _FakeItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocation_1 extends _i1.SmartFake implements _i3.Location {
  _FakeLocation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i4.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Item>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i2.Item>>.value(<_i2.Item>[]),
          )
          as _i5.Future<List<_i2.Item>>);

  @override
  _i5.Future<_i2.Item?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i2.Item?>.value(),
          )
          as _i5.Future<_i2.Item?>);

  @override
  _i5.Future<List<_i2.Item>> getByLocationId(int? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getByLocationId, [locationId]),
            returnValue: _i5.Future<List<_i2.Item>>.value(<_i2.Item>[]),
          )
          as _i5.Future<List<_i2.Item>>);

  @override
  _i5.Future<List<_i2.Item>> getByContainerId(int? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByContainerId, [containerId]),
            returnValue: _i5.Future<List<_i2.Item>>.value(<_i2.Item>[]),
          )
          as _i5.Future<List<_i2.Item>>);

  @override
  _i5.Future<List<_i2.Item>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i5.Future<List<_i2.Item>>.value(<_i2.Item>[]),
          )
          as _i5.Future<List<_i2.Item>>);

  @override
  _i5.Future<_i2.Item> create(_i2.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#create, [item]),
            returnValue: _i5.Future<_i2.Item>.value(
              _FakeItem_0(this, Invocation.method(#create, [item])),
            ),
          )
          as _i5.Future<_i2.Item>);

  @override
  _i5.Future<_i2.Item> update(_i2.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i5.Future<_i2.Item>.value(
              _FakeItem_0(this, Invocation.method(#update, [item])),
            ),
          )
          as _i5.Future<_i2.Item>);

  @override
  _i5.Future<bool> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countByLocationId(int? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#countByLocationId, [locationId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countByContainerId(int? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#countByContainerId, [containerId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i6.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Location>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i3.Location>>.value(<_i3.Location>[]),
          )
          as _i5.Future<List<_i3.Location>>);

  @override
  _i5.Future<_i3.Location?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i3.Location?>.value(),
          )
          as _i5.Future<_i3.Location?>);

  @override
  _i5.Future<_i3.Location?> getByQrCodeId(String? qrCodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getByQrCodeId, [qrCodeId]),
            returnValue: _i5.Future<_i3.Location?>.value(),
          )
          as _i5.Future<_i3.Location?>);

  @override
  _i5.Future<List<_i3.Location>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i5.Future<List<_i3.Location>>.value(<_i3.Location>[]),
          )
          as _i5.Future<List<_i3.Location>>);

  @override
  _i5.Future<_i3.Location> create(_i3.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#create, [location]),
            returnValue: _i5.Future<_i3.Location>.value(
              _FakeLocation_1(this, Invocation.method(#create, [location])),
            ),
          )
          as _i5.Future<_i3.Location>);

  @override
  _i5.Future<_i3.Location> update(_i3.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#update, [location]),
            returnValue: _i5.Future<_i3.Location>.value(
              _FakeLocation_1(this, Invocation.method(#update, [location])),
            ),
          )
          as _i5.Future<_i3.Location>);

  @override
  _i5.Future<bool> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}
